# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbQuery < Formula
  desc "Run SQL against configured hosts via native database clients"
  homepage "https://github.com/geraldcsoftware/db-query"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/geraldcsoftware/db-query/releases/download/v0.1.0/db-query_0.1.0_darwin_amd64.tar.gz"
    sha256 "124c8465856a6b0afe0b0e3695873327848ba61fa1fe837a40de86cdf3e11344"

    define_method(:install) do
      bin.install "db-query"
      generate_completions_from_executable(bin/"db-query", "completion", shells: [:zsh])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/geraldcsoftware/db-query/releases/download/v0.1.0/db-query_0.1.0_darwin_arm64.tar.gz"
    sha256 "9a6c0865ced9dd9c8c300942ae100b1f51521b2d85fe2550f252b18068685d63"

    define_method(:install) do
      bin.install "db-query"
      generate_completions_from_executable(bin/"db-query", "completion", shells: [:zsh])
    end
  end

  test do
    system "#{bin}/db-query", "version"
  end
end
