# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabStats < Formula
  desc "Beautiful interactive terminal UI for viewing your GitLab activity statistics"
  homepage "https://github.com/geraldcsoftware/git-stats"
  version "0.1.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.1.0-beta.1/gitlab-stats_darwin_amd64.tar.gz"
      sha256 "6ed8dab7e48212fcb99215a3a3bafe4670d1de456928f10982b113173df4c05c"

      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.1.0-beta.1/gitlab-stats_darwin_arm64.tar.gz"
      sha256 "d4b71d5d596dbb87a56d7199d009b0462b8f34a8fc7a47571351b374cc798d5d"

      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.1.0-beta.1/gitlab-stats_linux_amd64.tar.gz"
      sha256 "7d01219a75f64894664915ddbdafc9ceb689f6acd272450d80694ea03ae0cb33"
      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.1.0-beta.1/gitlab-stats_linux_arm64.tar.gz"
      sha256 "5345ce6b53935485ed70c4f6229cb7a2bcefcc614ca955d0fe99a8657a53f902"
      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
  end

  test do
    system "#{bin}/gitlab-stats", "--help"
  end
end
