# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Playbook < Formula
  desc "CLI tool for running Ansible playbooks"
  homepage "https://github.com/geraldcsoftware/playbook"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.1.0/playbook_darwin_amd64.tar.gz"
      sha256 "ca6328695882e3270eb783b74a62e0c3637ddd4e918d6f04aada9ff24c0bfb77"

      define_method(:install) do
        bin.install "playbook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.1.0/playbook_darwin_arm64.tar.gz"
      sha256 "378fb5d5d2558fe73ad491388dedefd9d5e3d72d04871ecc3fbad3787af23bf7"

      define_method(:install) do
        bin.install "playbook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.1.0/playbook_linux_amd64.tar.gz"
      sha256 "7b099ebfe2dca41411688cba5770f5728ce69be5efaee2018c08e89018a523af"
      define_method(:install) do
        bin.install "playbook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.1.0/playbook_linux_arm64.tar.gz"
      sha256 "1f718e0122d4da6ce491d639cb2674b7278fccedb81cecedabc16715cf4210a0"
      define_method(:install) do
        bin.install "playbook"
      end
    end
  end
end
