# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshx < Formula
  desc "SSH helper tool for managing and connecting to servers"
  homepage "https://github.com/geraldcsoftware/sshx"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.3/sshx_Darwin_x86_64.tar.gz"
      sha256 "38601ae6dc961441ea310b2c3e517c0ce6e666326ccb15b4efe582bc912856b5"

      def install
        bin.install "sshx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.3/sshx_Darwin_arm64.tar.gz"
      sha256 "1668945287eb87d52b358e0a635549ad1295b4143850cb0222b748119032d304"

      def install
        bin.install "sshx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.3/sshx_Linux_x86_64.tar.gz"
      sha256 "d7770be7958e8b2d90d9ac3ee7b24684e30dfacb80032cffd924b322d273b01c"
      def install
        bin.install "sshx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.3/sshx_Linux_arm64.tar.gz"
      sha256 "1ab4fe604e098d24b3e638269b5628e0d099fd4941d18d3e93b56b5889939f4d"
      def install
        bin.install "sshx"
      end
    end
  end
end
