# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshx < Formula
  desc "SSH helper tool for managing and connecting to servers"
  homepage "https://github.com/geraldcsoftware/sshx"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.2/sshx_Darwin_x86_64.tar.gz"
      sha256 "474352fef3f12f3028a567a86e39defd078c49e147c7bc84817aad38d75360c9"

      def install
        bin.install "sshx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.2/sshx_Darwin_arm64.tar.gz"
      sha256 "c9c1d0a69342d9b7b1c15af01a3c934d80ec24fa072e8795947271d725300c21"

      def install
        bin.install "sshx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.2/sshx_Linux_x86_64.tar.gz"
      sha256 "1dde68b3a20bb575d6334548eacd1cab1ef3a176e57fb702ffa23438a9b4fc38"
      def install
        bin.install "sshx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.2/sshx_Linux_arm64.tar.gz"
      sha256 "fd27fd3d52e9a65a79d4a78d69124c4cb1e70d353de0375ed9e304ba3396690d"
      def install
        bin.install "sshx"
      end
    end
  end
end
