# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshx < Formula
  desc "SSH helper tool for managing and connecting to servers"
  homepage "https://github.com/geraldcsoftware/sshx"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.5/sshx_Darwin_x86_64.tar.gz"
      sha256 "f4a042b47a2b53a5a864e35cb3599652f5d3a73e869e19e7e4fc27eafebff840"

      define_method(:install) do
        bin.install "sshx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.5/sshx_Darwin_arm64.tar.gz"
      sha256 "871e1c147a88d51d411040020d2ec767c688f8484e7782e9a0d7b72608db844e"

      define_method(:install) do
        bin.install "sshx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.5/sshx_Linux_x86_64.tar.gz"
      sha256 "3e8d7f17544e286aaa8f38a380b2660d75db80234d5cc633f41ca6118634cfce"
      define_method(:install) do
        bin.install "sshx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.5/sshx_Linux_arm64.tar.gz"
      sha256 "1d95e632cc88166e3e5e786bb63153510b8fb3e7c141fb4499403d25836dc1cb"
      define_method(:install) do
        bin.install "sshx"
      end
    end
  end
end
