# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbQuery < Formula
  desc "Run SQL against configured hosts via native database clients"
  homepage "https://github.com/geraldcsoftware/db-query"
  version "0.9.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/geraldcsoftware/db-query/releases/download/v0.9.0/db-query_0.9.0_darwin_amd64.tar.gz"
    sha256 "d96713bf329253ab3989fd7d76cf3946de46dd9b6f3c30bcf1e980a1e0cf1cc0"

    define_method(:install) do
      bin.install "db-query"
      generate_completions_from_executable(bin/"db-query", "completion", shells: [:zsh])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/geraldcsoftware/db-query/releases/download/v0.9.0/db-query_0.9.0_darwin_arm64.tar.gz"
    sha256 "a6837db70a5563c9fe622878508dbddb7087dfea4480cd2db0a6f1154d904e84"

    define_method(:install) do
      bin.install "db-query"
      generate_completions_from_executable(bin/"db-query", "completion", shells: [:zsh])
    end
  end

  test do
    system "#{bin}/db-query", "version"
  end
end
