# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbQuery < Formula
  desc "Run SQL against configured hosts via native database clients"
  homepage "https://github.com/geraldcsoftware/db-query"
  version "0.4.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/geraldcsoftware/db-query/releases/download/v0.4.0/db-query_0.4.0_darwin_amd64.tar.gz"
    sha256 "599c0c11c4760f716cedf2bca43d314ca59c09f8501769d94144077dc2a01611"

    define_method(:install) do
      bin.install "db-query"
      generate_completions_from_executable(bin/"db-query", "completion", shells: [:zsh])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/geraldcsoftware/db-query/releases/download/v0.4.0/db-query_0.4.0_darwin_arm64.tar.gz"
    sha256 "94a842bd908912874c3f5b192de4d204660169ecae2ec19db21d1d1bee21947b"

    define_method(:install) do
      bin.install "db-query"
      generate_completions_from_executable(bin/"db-query", "completion", shells: [:zsh])
    end
  end

  test do
    system "#{bin}/db-query", "version"
  end
end
