# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbQuery < Formula
  desc "Run SQL against configured hosts via native database clients"
  homepage "https://github.com/geraldcsoftware/db-query"
  version "0.10.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/geraldcsoftware/db-query/releases/download/v0.10.0/db-query_0.10.0_darwin_amd64.tar.gz"
    sha256 "4d38c138036fb6c8c9cd4bdc614fed73de55b74cad7bf7c8e4e3ca2db6de7218"

    define_method(:install) do
      bin.install "db-query"
      generate_completions_from_executable(bin/"db-query", "completion", shells: [:zsh])
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/geraldcsoftware/db-query/releases/download/v0.10.0/db-query_0.10.0_darwin_arm64.tar.gz"
    sha256 "be96548abb671725ba6d63a7d3a827253d691b660c40a0385b2abcc747f29ade"

    define_method(:install) do
      bin.install "db-query"
      generate_completions_from_executable(bin/"db-query", "completion", shells: [:zsh])
    end
  end

  test do
    system "#{bin}/db-query", "version"
  end
end
