# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabStats < Formula
  desc "Beautiful interactive terminal UI for viewing your GitLab activity statistics"
  homepage "https://github.com/geraldcsoftware/git-stats"
  version "0.1.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.1.0-beta.1/gitlab-stats_darwin_amd64.tar.gz"
      sha256 "13d3ff85b6f86a60fd2a1432dd3d90597ab9b40bf461a072341caaac54b3270c"

      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.1.0-beta.1/gitlab-stats_darwin_arm64.tar.gz"
      sha256 "0592218681b78d5e5734fb972b1908bb7fde2b924423e5796f4aa0b05d852d3f"

      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.1.0-beta.1/gitlab-stats_linux_amd64.tar.gz"
      sha256 "2a249ae3bdce16b173f2fb924eb930e58e4ea3af536c27447f017ecae67d0930"
      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.1.0-beta.1/gitlab-stats_linux_arm64.tar.gz"
      sha256 "07506bf43ce0436d264ca0084203f821f89ec80eab3c519070e50180c6a4548b"
      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
  end

  test do
    system "#{bin}/gitlab-stats", "--help"
  end
end
