# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabStats < Formula
  desc "Beautiful interactive terminal UI for viewing your GitLab activity statistics"
  homepage "https://github.com/geraldcsoftware/git-stats"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.2.0/gitlab-stats_darwin_amd64.tar.gz"
      sha256 "f5063244211302a54ef37cc36108ae6c6b8dd147c50d94099579fd0ea5403905"

      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.2.0/gitlab-stats_darwin_arm64.tar.gz"
      sha256 "7636f70827ea941cecb5cd2c76521c4057cb284ed3159e0f236719b33aaa6135"

      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.2.0/gitlab-stats_linux_amd64.tar.gz"
      sha256 "6e669990f51bb5cdd9d73a791e50ea2bbd0d7800e4dac5ec26b6a355e4a5710e"
      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.2.0/gitlab-stats_linux_arm64.tar.gz"
      sha256 "6d7a5ecef11d8863a0939e6218c4555245cca88c1ed20d278d549b47be362751"
      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
  end

  test do
    system "#{bin}/gitlab-stats", "--help"
  end
end
