# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabStats < Formula
  desc "Beautiful interactive terminal UI for viewing your GitLab activity statistics"
  homepage "https://github.com/geraldcsoftware/git-stats"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.2.1/gitlab-stats_darwin_amd64.tar.gz"
      sha256 "9e47ec87fc38f88f4716f2e55f019c6640c87590dcd0a794b71ca3e3b442e888"

      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.2.1/gitlab-stats_darwin_arm64.tar.gz"
      sha256 "0b8ec24ca8003d7c58384abd7919e7f0ba5af3d5b497ef11ced0920a65664df8"

      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.2.1/gitlab-stats_linux_amd64.tar.gz"
      sha256 "09fc7c317b9736070d999fc12c4303c8f709e78e4493a66d6e53226db2b5d752"
      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/gitlab-stats/releases/download/v0.2.1/gitlab-stats_linux_arm64.tar.gz"
      sha256 "fa87dc148571df21f3c1226140141b291e94d815a868ccfdc39c20df355e34ee"
      define_method(:install) do
        bin.install "gitlab-stats"
      end
    end
  end

  test do
    system "#{bin}/gitlab-stats", "--help"
  end
end
