# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Playbook < Formula
  desc "CLI tool for running Ansible playbooks"
  homepage "https://github.com/geraldcsoftware/playbook"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.1.1/playbook_darwin_amd64.tar.gz"
      sha256 "c0d3982042737dc742ed9a41b550b24da685d22fd728a2fcf11355071769cf3f"

      define_method(:install) do
        bin.install "playbook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.1.1/playbook_darwin_arm64.tar.gz"
      sha256 "c6c5d37d55fa0b1fe8bbfa4af0b07e0b5ccd854ae601ca84b9588a1809e2ffcd"

      define_method(:install) do
        bin.install "playbook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.1.1/playbook_linux_amd64.tar.gz"
      sha256 "87d9594e0c1855793bed7520b6ba490f7f244ab40d60dda741a4259d7d644d2e"
      define_method(:install) do
        bin.install "playbook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.1.1/playbook_linux_arm64.tar.gz"
      sha256 "5282884d6f2eb2b754f37f4a34609f5e58be0931b2aaaba3f59adeeb040664c6"
      define_method(:install) do
        bin.install "playbook"
      end
    end
  end
end
