# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Playbook < Formula
  desc "CLI tool for running Ansible playbooks"
  homepage "https://github.com/geraldcsoftware/playbook"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.2.2/playbook_darwin_amd64.tar.gz"
      sha256 "93026eb9487f114a806f1ab7d43d11584b09bd821f9ab86f2a3228440707386e"

      define_method(:install) do
        bin.install "playbook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.2.2/playbook_darwin_arm64.tar.gz"
      sha256 "2c1ac393c38fd185bbe6b692538da174d3d6a0cf1556b455eef860536c5ba340"

      define_method(:install) do
        bin.install "playbook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.2.2/playbook_linux_amd64.tar.gz"
      sha256 "1d81df8e2208fedb9420aac23ad1b212e59defe57735d1d81468342eab2f05a3"
      define_method(:install) do
        bin.install "playbook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.2.2/playbook_linux_arm64.tar.gz"
      sha256 "9ed8bc04bb80eb06817f24e189630f7271cc6c125bd3b0f5ff7d47d4d7f2b70c"
      define_method(:install) do
        bin.install "playbook"
      end
    end
  end
end
