# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Playbook < Formula
  desc "CLI tool for running Ansible playbooks"
  homepage "https://github.com/geraldcsoftware/playbook"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.3.0/playbook_darwin_amd64.tar.gz"
      sha256 "9286c1ea36ecbfba63696dd045007797331cbcfbd690344fe15fc25632249015"

      define_method(:install) do
        bin.install "playbook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.3.0/playbook_darwin_arm64.tar.gz"
      sha256 "939632b28d56a78f622c489f8d74df911c72044f4234b227a230d87fd1d7d5ee"

      define_method(:install) do
        bin.install "playbook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.3.0/playbook_linux_amd64.tar.gz"
      sha256 "9a8c9e6c970187019c1666a5a27e1b9853a51eb9a5882f66a7ad3130d69dc22b"
      define_method(:install) do
        bin.install "playbook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/playbook/releases/download/v0.3.0/playbook_linux_arm64.tar.gz"
      sha256 "ee4dc2e4cc426f63557c319bede55af3c8151720d5bd067edda2d0e90ca1a291"
      define_method(:install) do
        bin.install "playbook"
      end
    end
  end
end
