# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Space < Formula
  desc "Multi-repo workspace manager for git worktrees"
  homepage "https://github.com/geraldcsoftware/workspace-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/workspace-cli/releases/download/v0.1.2/space_0.1.2_darwin_amd64.tar.gz"
      sha256 "010f246e5f824fbac5f988f189b95c36d9d0927266793e3037b689f6ed7f2110"

      define_method(:install) do
        bin.install "space"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/workspace-cli/releases/download/v0.1.2/space_0.1.2_darwin_arm64.tar.gz"
      sha256 "385ab7715712915fe7f8e6b984d2d2fd1b2690fe560306b33f1c3a549c1e8f48"

      define_method(:install) do
        bin.install "space"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/workspace-cli/releases/download/v0.1.2/space_0.1.2_linux_amd64.tar.gz"
      sha256 "048dd0f07c1845fcb3f0a5f0d7b01c78cb9cb37051d5914a2f00b37afd7b1a28"
      define_method(:install) do
        bin.install "space"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/workspace-cli/releases/download/v0.1.2/space_0.1.2_linux_arm64.tar.gz"
      sha256 "45351283cbcc781a0fbef37a8ef11322713f1552b1c51bef623f9045e9b94a9b"
      define_method(:install) do
        bin.install "space"
      end
    end
  end

  test do
    system "#{bin}/space", "help"
  end
end
