# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Space < Formula
  desc "Multi-repo workspace manager for git worktrees"
  homepage "https://github.com/geraldcsoftware/workspace-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/workspace-cli/releases/download/v0.2.0/space_0.2.0_darwin_amd64.tar.gz"
      sha256 "0fa4b664a0d1e92d4fccef13501aa4b2e39014f2accd1880168e572423f710c8"

      define_method(:install) do
        bin.install "space"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/workspace-cli/releases/download/v0.2.0/space_0.2.0_darwin_arm64.tar.gz"
      sha256 "b100dc36ae78cced8a07386ac6fd1b6bdd9a149b59b4dfa548ebffbe91b498a0"

      define_method(:install) do
        bin.install "space"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/workspace-cli/releases/download/v0.2.0/space_0.2.0_linux_amd64.tar.gz"
      sha256 "edc8339e96d5a37bcf8a42cf852fe76aa557c77da8b531d925f098bfec5d3641"
      define_method(:install) do
        bin.install "space"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/workspace-cli/releases/download/v0.2.0/space_0.2.0_linux_arm64.tar.gz"
      sha256 "a8bec664ab87d6f6fc1f4f355bb90c537707fe9efd22996621493b44cf104e2e"
      define_method(:install) do
        bin.install "space"
      end
    end
  end

  test do
    system "#{bin}/space", "help"
  end
end
