# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshx < Formula
  desc "SSH helper tool for managing and connecting to servers"
  homepage "https://github.com/geraldcsoftware/sshx"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.6/sshx_Darwin_x86_64.tar.gz"
      sha256 "e91a53c342a0ef8482dd1a3d4a20c2627fb5ccc1a7f30f13f071ef9aa1864d91"

      define_method(:install) do
        bin.install "sshx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.6/sshx_Darwin_arm64.tar.gz"
      sha256 "679c96b0e37345f2aa4881e63e7ec5784d6f42208a1f71a5be517c06f513883c"

      define_method(:install) do
        bin.install "sshx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.6/sshx_Linux_x86_64.tar.gz"
      sha256 "fa89ee2081e03ae789164c4336b5aab513a76c1189507074765d2cf8a99caab6"
      define_method(:install) do
        bin.install "sshx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/sshx/releases/download/v0.0.6/sshx_Linux_arm64.tar.gz"
      sha256 "7bef2d9c1d552b0479b19040eadd617a7eaac3daa68045938520935a94b702a0"
      define_method(:install) do
        bin.install "sshx"
      end
    end
  end
end
