# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WtCmd < Formula
  desc "Symlink untracked personal files into git worktrees (git wt)"
  homepage "https://github.com/geraldcsoftware/worktree-cmd"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geraldcsoftware/worktree-cmd/releases/download/v0.1.0/wt-cmd_darwin_amd64.tar.gz"
      sha256 "cd5ced7a6d55c330f9d1586a4374424a56cf9cf854913113a61bee7a53d21fb0"

      define_method(:install) do
        bin.install "git-wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geraldcsoftware/worktree-cmd/releases/download/v0.1.0/wt-cmd_darwin_arm64.tar.gz"
      sha256 "961627457df70945b59f4c39b9f750ee7b22f27d446d26a155adfecf000bc6aa"

      define_method(:install) do
        bin.install "git-wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/worktree-cmd/releases/download/v0.1.0/wt-cmd_linux_amd64.tar.gz"
      sha256 "3a3297ecf3e5c73c47d7577da37f56527e5b2fea36f16f2ebc310f4c49e04837"
      define_method(:install) do
        bin.install "git-wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geraldcsoftware/worktree-cmd/releases/download/v0.1.0/wt-cmd_linux_arm64.tar.gz"
      sha256 "f042235711ffa1b751404b987074209827790c131e5ea7873b1b33be60499bf5"
      define_method(:install) do
        bin.install "git-wt"
      end
    end
  end

  test do
    system "#{bin}/git-wt", "--version"
  end
end
